[project]
name = "drehmal-temporal-stasis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
 "anvil-parser>=0.9.0",
 "joblib>=1.5.1",
 "nbt>=1.5.1",
 "nbtlib>=2.0.4",
]

[tool.ruff]
line-length = 120
